### ISSUE TITLE
`concat` method does work as expected - bulk insert

### ISSUE THREAD

**Issue by ralphsmith80** [typicode/lowdb#165]
I was looking at how I could do bulk insert with `json-server` and I dug into lowdb to see how to get that support. I looks like the `concat` method is not working.

Here's a simple example:
```
var low = require('lowdb')
var db = low('db.json')
db.defaults({posts: []})
db.write()
db.get('posts').push({ "id": 0})
db.write()
db.get('posts').value()
db.get('posts').concat([{ "id": 1}])
db.write()
db.get('posts').value()
```

**expected results**
```json
{
  "posts": [
    {
      "id": 0
    },
    {
      "id": 1
    }
  ]
}
```

**actual results**
```
{
  "posts": [
    {
      "id": 0
    }
  ]
}
```

**Comment by ralphsmith80** [comment]
I started wondering if the fact that `concat` is an immutable operation was causing this not to work. 

Attempting a mutable `push` with array in ES5
```
Array.prototype.push.apply(db.get('posts'), [{ "id": 2}])
db.write()
db.get('posts').value()
```

**results - no dice**
```
{
  "posts": [
    {
      "id": 0
    }
  ]
}
```

Attempting a mutable `push` with array in ES6
```
db.get('posts').push(...[{ "id": 1}])
db.write()
db.get('posts').value()
```

**results - success!**
```
{
  "posts": [
    {
      "id": 0
    },
    {
      "id": 1
    }
  ]
}
```

That works, but I still need to figure out how to incorporate that into [json-server](https://github.com/typicode/json-server) and I still wondering if the `concat` should handle this. I think it would still make sense to use `concat`.

**Comment by typicode** [comment]
Hi @ralphsmith80,

The execution of chained methods is lazy, you need to call `.write` or `.value` at the end or nothing will happen.

```js
db.get('posts')
  .push({ id: 1 })
  .write()

// it's equivalent to
db.get('posts')
  .push({ id: 1 })
  .value()

db.write()
```

And you're right, the issue was that `concat` return a new array and doesn't modify the original array.

So `push(...array).write` is one way, if you prefer to use `concat` you can do:

```js
const newPosts = db.get('posts').concat(array).value()
db.set('posts', newPosts).write()
```

**Comment by ralphsmith80** [comment]
I get an error if I chain `write`

```
db.set('posts', newPosts).write()
TypeError: db.set(...).write is not a function
    at repl:1:27
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
```

But the following works:
```
var newPosts = db.get('posts').concat([{ "id": 1}]).value()
db.set('posts', newPosts)
db.write()
```

That should satisfy my use case so I'm closing this. Thanks for the comments.

**Comment by ralphsmith80** [comment]
> I get an error if I chain `write`

I think I was probably on an older version. The chaining works with `^0.15.0`.
