### ISSUE TITLE
Can't import JSONFile from "lowdb/node" import.

### ISSUE THREAD

**Issue by Trystan-SA** [typicode/lowdb#554]
When I use `import {JSONFile} from 'lowdb/lib/node'` it return the following error message. 

``` 
[ERROR] Could not resolve "lowdb/lib/node"
    src/users.ts:2:23:
      2 │ import {JSONFile} from 'lowdb/lib/node'
        ╵                        ~~~~~~~~~~~~~~~~
  The path "./lib/node" is not exported by package "lowdb":
```
I'm using Esbuild, I tried to make this package external, or tried find another import path, but I can't make it work without modifying the lowdb source code. This is what I did :

index.js
```
export * from './adapters/Memory.js';
export * from './adapters/MemorySync.js';
export * from './Low.js';
export * from './LowSync.js';
+ export * from './node.js';
```

I tried to use the documentation path `import {JSONFile} from 'lowdb/node'` but typescript can't find the module.

**Comment by typicode** [comment]
Hi,

Could you please check that you're using latest lowdb version? I have it working with v5.0.5 and TypeScript in a project I'm working on.

**Comment by nooptr** [comment]
@typicode 
I also had the same problem.
I use mac m1 pro. Using node 16.14.0

**Comment by Trystan-SA** [comment]
I use the latest 5.0.5 version.

**Comment by jasonbarone** [comment]
Issue happens on the lowdb/browser imports too. I can reproduce using a default Next.js project + lowdb: https://github.com/jasonbarone/lowdb-type-error-test

**Comment by typicode** [comment]
Can you try setting `"type": "module"` in your package.json?
Here's also how you can test locally:

`package.json`

```json
{
  "name": "lowdb-test",
  "version": "1.0.0",
  "type": "module",
  "dependencies": {
    "lowdb": "^5.0.5"
  },
  "devDependencies": {
    "@sindresorhus/tsconfig": "^3.0.1",
    "typescript": "^4.8.4"
  }
}
```

`tsconfig.json`

```json
{
  "extends": "@sindresorhus/tsconfig",
  "compilerOptions": {
    "outDir": "./lib"
  }
}
```

`src/index.ts`

```typescript
import { Low } from 'lowdb'
import { JSONFile } from 'lowdb/node'
```

```shell
/tmp/lowdb-test is 📦 v1.0.0 via  v19.0.0 
❯ npm x tsc
src/index.ts:1:1 - error TS6133: 'Low' is declared but its value is never read.

1 import { Low } from 'lowdb'
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:2:1 - error TS6133: 'JSONFile' is declared but its value is never read.

2 import { JSONFile } from 'lowdb/node'
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/index.ts:1
```

**Comment by Trystan-SA** [comment]
Still not working. For `import {JSONFile} from 'lowdb/lib/node'` I get :
```
X [ERROR] Could not resolve "lowdb/lib/node"
  The path "./lib/node" is not exported by package "lowdb":
  The file "./lib/node.js" is exported at path "./node":
  Import from "lowdb/node" to get the file "node_modules/lowdb/lib/node.js":
 You can mark the path "lowdb/lib/node" as external to exclude it from the bundle, which will
  remove this error.
```

If I do `import {JSONFile} from 'lowdb/node` it says the path is not found. Probably because it resolve lowdb package starting from the basepath and not from lowdb/lib folder.

**Comment by typicode** [comment]
Hhmm I don't know why you're still getting this error. You can check https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#im-having-problems-with-esm-and-typescript

Mapping from `lowdb/node` to `lowdb/lib/node.js` is done here btw:
https://github.com/typicode/lowdb/blob/main/package.json#L32

**Comment by tkafka** [comment]
+1 here - typescript project with Next.js. 

`import { JSONFile } from 'lowdb/node.js'`:
When running `next build`, this fails with `Type error: Cannot find module 'lowdb/node.js' or its corresponding type declarations.` in ` Linting and checking validity of types` phase.

`import { JSONFile } from 'lowdb/lib/node.js'`
The `Linting and checking validity of types` phase completes fine, but then `Creating an optimized production build` fails with `Module not found: Package path ./lib/node.js is not exported from package <project-path>/node_modules/lowdb (see exports field in <project-path>/node_modules/lowdb/package.json)`

It seems that the assignment `"./node": "./lib/node.js",` in package.json is something that one of the tools in pipeline cannot handle.

**Comment by 9a-aaaaaaaa** [comment]
+1

**Comment by 9a-aaaaaaaa** [comment]
It's totally unusable. If we don't fix this

**Comment by typicode** [comment]
@tkafka it should be `import { JSONFile } from 'lowdb/node'` (removed `.js`)

**Comment by tkafka** [comment]
@typicode Yes, it doesn't work with Next.js - `next dev` runs fine, but `next build` fails at type checking.

I have made a simplest possible repo to reproduce this: https://github.com/tkafka/lowdb-node-fail

**Comment by Sec-ant** [comment]
I believe this has something to do with the ts es module resolution strategy. I ran into the issue too, but I switched my project to pure esm config later and everything works. I suggest using the latest typescript version and set `moduleResolution` to `NodeNext` in your `tsconfig.json`:

```json
{
  "compilerOptions": {
    "moduleResolution": "NodeNext",
}
```

**Comment by Sec-ant** [comment]
> However, the build still seems to fail:
That's disappointing. My guess is that there are some inconsistent behaviours.
> 
There seems to be already several issue and discussions: https://github.com/vercel/next.js/issues/35572 https://github.com/vercel/next.js/discussions/41189

**Comment by typicode** [comment]
I think it would be worth it reporting to Next.js if there's no duplicate issue already.

In any case, AFAICT, lowdb works with Node + TypeScript with the example provided above and package config is correct. So I'm not sure what can be done at lowdb's level to make it work.

It's fine to stay on v3 meanwhile. v5 is a maintenance update and fixes issues with front-end tools like Vite.

**Comment by Smiley43210** [comment]
I'm able to reproduce this with just lowdb + TypeScript. See https://github.com/Smiley43210/cannot-find-lowdb for minimum repro.

lowdb@5.05
typescript@4.8.4

**Comment by Sec-ant** [comment]
@Smiley43210 You should use `nodenext` for `moduleResolution` in `tsconfig.json`, like I said here: https://github.com/typicode/lowdb/issues/554#issuecomment-1293154430

**Comment by Smiley43210** [comment]
Sorry, I got confused and thought that was something specific to Next.js

**Comment by or2008** [comment]
have the same issue, unfoutrnly setting moduleResolution to 'nodenext' is casuing other issues in my application :(

<img width="954" alt="image" src="https://user-images.githubusercontent.com/3414979/199071303-b63e8ceb-e40b-4e73-ac40-105b8798083d.png">

**Comment by didac-pf** [comment]
Same problem in NestJS (not NextJS). Changing moduleResolution breaks all other imports.

**Comment by jsternadel** [comment]
Same problem here.  Setting `"moduleResolution": "NodeNext"` breaks tseveral other imports.  Rolled back to v4 and everything is working for now.

**Comment by vedantroy** [comment]
This breaks with V3 as well.

**Comment by GrinZero** [comment]
try this solution:

# useage
```tsx
import { JSONFile } from 'lowdb/node'
import type { JSONFile as JSONFileType } from 'lowdb/lib/node'

type DBData = {
  hosts: string[]
}
const adapter = new JSONFile<DBData>(path.join(USER_DATA_PATH, 'db.json')) as JSONFileType<DBData>
```

# .d.ts
```tsx
declare module 'lowdb/node' {
  export function JSONFile<T>(path: string): void
}
// you can add more
```

**Comment by bartektartanus** [comment]
Same issue with this import:
`import {LocalStorage} from 'lowdb/browser';`

**Comment by arimgibson** [comment]
I'm actually questioning if this is a bug with esbuild instead of Next.js or Nuxt.js (both use esbuild)... encountering the same error without Next.js or Nuxt.js. Can provide more info if needed, but error message is the same as others have reported

**Comment by joycollector** [comment]
For we works like this
```
declare module "lowdb/node" {
  export * from "lowdb/lib/node";
}
```

**Comment by tkafka** [comment]
I can confirm @joycollector's solution works for me as well, thank you!

For the record, I have put `lowdb.d.ts` file into `<project_root>/definitions` in my next.js (Next 13) app.

**Comment by dtroydev** [comment]
Another option is to patch up lowdb (and leave everything else alone):

1. `npm i -D patch-package`
2. add `export * from './node.js'` to the end of `node_modules/lowdb/lib/index.js` and `node_modules/lowdb/lib/index.d.ts`
3. `npx patch-package lowdb`
4. add `"postinstall": "patch-package"` to scrips in package.json

This way, everytime you reinstall modules you will get that patch applied.

**Comment by Valexr** [comment]
> ```tsx
> declare module 'lowdb/node' {
>   export function JSONFile<T>(path: string): void
> }
> ```

I think, this declaration mast be in lib d.ts files...🤔

![Screenshot 2023-01-30 at 15 06 16](https://user-images.githubusercontent.com/5656366/215472543-1c052265-07e8-4c88-8560-0082e670949b.jpg)
this is strange d.ts file content...🤔

`tsc` will declare types fine🤷🏻‍♂️

![Screenshot 2023-01-30 at 15 14 03](https://user-images.githubusercontent.com/5656366/215474259-b9576ceb-4aa9-434f-aaae-60d70209b0de.jpg)

true declaration live in `lowdb/lib/adapters/JSONFile.d.ts`

**Comment by molvqingtai** [comment]
I set `"moduleResolution": "NodeNext"` to work properly.

**Comment by weoreference** [comment]
Same issue here with plain Typescript. This is a deal breaker for me. Something so basic (even shown in the official tutorial) should work with absolutely no issues. Abstract this problem away. Too much configuration from the get-go

**Comment by fransyozef** [comment]
yeah I second @weoreference First I thought this package would be very nice to have as mock database on local machine. But just trying to install / fix

`import { JSONFile } from 'lowdb/node';`

is just breaking everything in my code. to bad :(

**Comment by CKGrafico** [comment]
it works now @typicode :)

**Comment by wxfred** [comment]
> Could you please retry with lowdb v6.0.1 which contains @Krak798's fix #569

Still have some problem in electron

**Comment by colining** [comment]
not work in electron

**Comment by Krak798** [comment]
could you please give more information about the error?

**Comment by Krak798** [comment]
@colining 

[Here](https://github.com/colining/erb-lowdb-test/blob/ecd0dc505b791680967f11fd689ecbd8e507612b/src/main/db.ts#L2) you are importing JSONFileSync from the wrong path. Check usage [here](https://github.com/typicode/lowdb/blob/main/README.md#usage).

```diff
- import { JSONFileSync, LowSync } from "lowdb";
+ import { LowSync } from "lowdb";
+ import { JSONFileSync } from "lowdb/node"; // in electron
```

**Comment by wxfred** [comment]
> @colining
> 
> [Here](https://github.com/colining/erb-lowdb-test/blob/ecd0dc505b791680967f11fd689ecbd8e507612b/src/main/db.ts#L2) you are importing JSONFileSync from the wrong path. Check usage [here](https://github.com/typicode/lowdb/blob/main/README.md#usage).
> 
> ```diff
> - import { JSONFileSync, LowSync } from "lowdb";
> + import { LowSync } from "lowdb";
> + import { JSONFileSync } from "lowdb/node"; // in electron
> ```

```
// background.js
import { LowSync } from "lowdb"
import { JSONFileSync } from "lowdb/node"
```

```
This dependency was not found:

* lowdb/node in ./src/background.js

To install it, you can run: npm install --save lowdb/node
```

**Comment by jakeershareef** [comment]
Error in splitPdfPathHandler: [Error: ENOENT: no such file or directory, rename 'C:\Users\jakee\OneDrive\Desktop\lis-scan-docs\desktop-scan-docs\db\.scan.json.tmp' -> 'C:\Users\jakee\OneDrive\Desktop\lis-scan-docs\desktop-scan-docs\db\scan.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'rename',
  path: 'C:\\Users\\jakee\\OneDrive\\Desktop\\lis-scan-docs\\desktop-scan-docs\\db\\.scan.json.tmp',
  dest: 'C:\\Users\\jakee\\OneDrive\\Desktop\\lis-scan-docs\\desktop-scan-docs\\db\\scan.json'
}

i am getting this error while processing files using electron application, how can i resolve this issue.

**Comment by Arnique** [comment]
This fix

```
declare module 'lowdb/node' {
  export function JSONFile<T>(path: string): void
}
```
Not working in version 7.0.1
